// Shared by the command-line demo and Postman collection generator.
const location = { name: 'Demo laboratorija', address: 'Studentų g. 50, Kaunas', description: 'Automatinė API demonstracija' };
const device = { name: 'Demo maršrutizatorius', type: 'Router', ipAddress: '10.10.0.1', macAddress: '02:AA:00:00:00:01', status: 'Online' };
const client = { name: 'Demo kompiuteris', type: 'Computer', ipAddress: '10.10.0.10', macAddress: '02:BB:00:00:00:01' };
const L = '/api/locations/{{locationId}}';
const D = L + '/devices/{{deviceId}}';
const C = D + '/clients/{{clientId}}';
export const scenarios = [
  { name: 'API and PostgreSQL health', method: 'GET', path: '/health', status: 200, equals: { status: 'healthy' } },
  { name: 'Protected endpoint without token', method: 'GET', path: '/api/locations', status: 401 },
  { name: 'Reject role escalation during registration', method: 'POST', path: '/api/auth/register', body: { email: '{{ownerEmail}}', password: '{{password}}', role: 'Admin' }, status: 400 },
  { name: 'Register owner', method: 'POST', path: '/api/auth/register', body: { email: '{{ownerEmail}}', password: '{{password}}' }, status: 201, save: { ownerToken: 'accessToken', ownerId: 'user.id' }, equals: { 'user.role': 'User' } },
  { name: 'Duplicate email', method: 'POST', path: '/api/auth/register', body: { email: '{{ownerEmail}}', password: '{{password}}' }, status: 409 },
  { name: 'Wrong password', method: 'POST', path: '/api/auth/login', body: { email: '{{ownerEmail}}', password: 'WrongPassword123!' }, status: 401 },
  { name: 'Login owner', method: 'POST', path: '/api/auth/login', body: { email: '{{ownerEmail}}', password: '{{password}}' }, status: 200, save: { ownerToken: 'accessToken' }, jwtRole: 'User' },
  { name: 'Register another user', method: 'POST', path: '/api/auth/register', body: { email: '{{otherEmail}}', password: '{{password}}' }, status: 201, save: { otherToken: 'accessToken', otherId: 'user.id' } },
  { name: 'Login administrator', method: 'POST', path: '/api/auth/login', body: { email: '{{adminEmail}}', password: '{{adminPassword}}' }, status: 200, save: { adminToken: 'accessToken', adminId: 'user.id' }, jwtRole: 'Admin' },
  { name: 'Current user', method: 'GET', path: '/api/auth/me', token: 'ownerToken', status: 200, equals: { id: '{{ownerId}}', role: 'User' } },
  { name: '01 Create location', method: 'POST', path: '/api/locations', token: 'ownerToken', body: location, status: 201, save: { locationId: 'id' }, equals: { ownerId: '{{ownerId}}' } },
  { name: '02 List and filter locations', method: 'GET', path: '/api/locations?search=Demo&ownerId={{ownerId}}&pageSize=1', token: 'ownerToken', status: 200, equals: { total: 1, 'items.0.id': '{{locationId}}', pageSize: 1 } },
  { name: '03 Read location', method: 'GET', path: L, token: 'ownerToken', status: 200, equals: { name: location.name } },
  { name: '04 Update location', method: 'PUT', path: L, token: 'ownerToken', body: { ...location, name: 'Atnaujinta laboratorija' }, status: 200, equals: { name: 'Atnaujinta laboratorija' } },
  { name: '05 Create device', method: 'POST', path: L + '/devices', token: 'ownerToken', body: device, status: 201, save: { deviceId: 'id' }, equals: { locationId: '{{locationId}}' } },
  { name: '06 List and filter devices', method: 'GET', path: L + '/devices?type=Router&status=Online&search=Demo', token: 'ownerToken', status: 200, equals: { total: 1, 'items.0.id': '{{deviceId}}' } },
  { name: '07 Read device', method: 'GET', path: D, token: 'ownerToken', status: 200, equals: { ipAddress: device.ipAddress } },
  { name: '08 Update device', method: 'PUT', path: D, token: 'ownerToken', body: { ...device, status: 'Maintenance' }, status: 200, equals: { status: 'Maintenance' } },
  { name: '09 Create client', method: 'POST', path: D + '/clients', token: 'ownerToken', body: client, status: 201, save: { clientId: 'id' }, equals: { deviceId: '{{deviceId}}' } },
  { name: '10 List and filter clients', method: 'GET', path: D + '/clients?type=Computer&search=Demo', token: 'ownerToken', status: 200, equals: { total: 1, 'items.0.id': '{{clientId}}' } },
  { name: '11 Read client', method: 'GET', path: C, token: 'ownerToken', status: 200, equals: { name: client.name } },
  { name: '12 Update client', method: 'PUT', path: C, token: 'ownerToken', body: { ...client, name: 'Atnaujintas kompiuteris' }, status: 200, equals: { name: 'Atnaujintas kompiuteris' } },
  { name: 'Other user can read locations', method: 'GET', path: L, token: 'otherToken', status: 200 },
  { name: 'Other user can read devices', method: 'GET', path: D, token: 'otherToken', status: 200 },
  { name: 'Cannot update another user location', method: 'PUT', path: L, token: 'otherToken', body: location, status: 403 },
  { name: 'Cannot delete another user location', method: 'DELETE', path: L, token: 'otherToken', status: 403 },
  { name: 'Cannot create device in another user location', method: 'POST', path: L + '/devices', token: 'otherToken', body: device, status: 403 },
  { name: 'Cannot update another user device', method: 'PUT', path: D, token: 'otherToken', body: device, status: 403 },
  { name: 'Cannot delete another user device', method: 'DELETE', path: D, token: 'otherToken', status: 403 },
  ...['GET', 'POST'].map(method => ({ name: `Protect client collection ${method}`, method, path: D + '/clients', token: 'otherToken', ...(method === 'POST' ? { body: client } : {}), status: 403 })),
  ...['GET', 'PUT', 'DELETE'].map(method => ({ name: `Protect individual client ${method}`, method, path: C, token: 'otherToken', ...(method === 'PUT' ? { body: client } : {}), status: 403 })),
  { name: 'Admin can read private clients', method: 'GET', path: C, token: 'adminToken', status: 200 },
  { name: 'Admin can update another user location', method: 'PUT', path: L, token: 'adminToken', body: location, status: 200 },
  { name: 'Admin can update another user device', method: 'PUT', path: D, token: 'adminToken', body: device, status: 200 },
  { name: 'Admin can update another user client', method: 'PUT', path: C, token: 'adminToken', body: client, status: 200 },
  { name: 'Reject missing required fields', method: 'POST', path: '/api/locations', token: 'ownerToken', body: {}, status: 400 },
  { name: 'Reject blank name', method: 'PUT', path: L, token: 'ownerToken', body: { ...location, name: '   ' }, status: 400 },
  { name: 'Reject malformed JSON', method: 'POST', path: '/api/locations', token: 'ownerToken', raw: '{bad json', status: 400 },
  { name: 'Reject invalid IP', method: 'POST', path: L + '/devices', token: 'ownerToken', body: { ...device, ipAddress: 'not-an-ip' }, status: 400 },
  { name: 'Reject invalid MAC', method: 'POST', path: D + '/clients', token: 'ownerToken', body: { ...client, macAddress: 'invalid' }, status: 400 },
  { name: 'Reject invalid enum', method: 'POST', path: D + '/clients', token: 'ownerToken', body: { ...client, type: 'Invalid' }, status: 400 },
  { name: 'Reject invalid pagination', method: 'GET', path: '/api/locations?page=0&pageSize=101', token: 'ownerToken', status: 400 },
  { name: 'Reject invalid query filter', method: 'GET', path: L + '/devices?status=Invalid', token: 'ownerToken', status: 400 },
  { name: 'Duplicate device MAC', method: 'POST', path: L + '/devices', token: 'ownerToken', body: device, status: 409 },
  { name: 'Duplicate client MAC', method: 'POST', path: D + '/clients', token: 'ownerToken', body: client, status: 409 },
  { name: 'Unknown location returns 404', method: 'GET', path: '/api/locations/00000000-0000-0000-0000-000000000000', token: 'ownerToken', status: 404 },
  { name: 'Unknown device returns 404', method: 'GET', path: L + '/devices/00000000-0000-0000-0000-000000000000', token: 'ownerToken', status: 404 },
  { name: 'Unknown client returns 404', method: 'GET', path: D + '/clients/00000000-0000-0000-0000-000000000000', token: 'ownerToken', status: 404 },
  { name: 'Create second location for nesting test', method: 'POST', path: '/api/locations', token: 'ownerToken', body: { ...location, name: 'Antra vieta' }, status: 201, save: { secondLocationId: 'id' } },
  { name: 'Device cannot be accessed under wrong location', method: 'GET', path: '/api/locations/{{secondLocationId}}/devices/{{deviceId}}', token: 'ownerToken', status: 404 },
  { name: 'Client cannot be accessed under wrong location', method: 'GET', path: '/api/locations/{{secondLocationId}}/devices/{{deviceId}}/clients/{{clientId}}', token: 'ownerToken', status: 404 },
  { name: '13 Delete client', method: 'DELETE', path: C, token: 'ownerToken', status: 204 },
  { name: 'Deleted client is absent', method: 'GET', path: C, token: 'ownerToken', status: 404 },
  { name: '14 Delete device', method: 'DELETE', path: D, token: 'ownerToken', status: 204 },
  { name: 'Deleted device is absent', method: 'GET', path: D, token: 'ownerToken', status: 404 },
  { name: '15 Delete location', method: 'DELETE', path: L, token: 'ownerToken', status: 204 },
  { name: 'Deleted location is absent', method: 'GET', path: L, token: 'ownerToken', status: 404 },
  { name: 'Non-admin cannot list users', method: 'GET', path: '/api/users', token: 'ownerToken', status: 403 },
  { name: 'Non-admin cannot delete users', method: 'DELETE', path: '/api/users/{{otherId}}', token: 'ownerToken', status: 403 },
  { name: 'Admin lists users without password hashes', method: 'GET', path: '/api/users?search={{ownerEmail}}', token: 'adminToken', status: 200, equals: { total: 1, 'items.0.id': '{{ownerId}}' }, absent: ['items.0.passwordHash'] },
  { name: 'Admin cannot delete own account', method: 'DELETE', path: '/api/users/{{adminId}}', token: 'adminToken', status: 409 },
  { name: 'Logout owner', method: 'POST', path: '/api/auth/logout', token: 'ownerToken', status: 204 },
  { name: 'Logged-out JWT is rejected', method: 'GET', path: '/api/auth/me', token: 'ownerToken', status: 401 },
  { name: 'Admin deletes owner and remaining location', method: 'DELETE', path: '/api/users/{{ownerId}}', token: 'adminToken', status: 204 },
  { name: 'User deletion cascades to locations', method: 'GET', path: '/api/locations/{{secondLocationId}}', token: 'adminToken', status: 404 },
  { name: 'Admin deletes second user', method: 'DELETE', path: '/api/users/{{otherId}}', token: 'adminToken', status: 204 },
  { name: 'Deleted user JWT is rejected', method: 'GET', path: '/api/auth/me', token: 'otherToken', status: 401 },
  { name: 'Logout administrator', method: 'POST', path: '/api/auth/logout', token: 'adminToken', status: 204 },
];
